# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff802afcadcf4b6dbee2fa6cccbe7365438095cb5f4f7ce982a0e6365c0627a2ce6795376e27b493de0b1123cf0d690d44afbc022659fe37e0d78994c5240d86

test:
  secret_key_base: ab9f536f5fd3409fb8a0006397ce327178140a9e43a8010c40f50e156ac4c856aa982ebe771824d743a15f9a6b6ca3b8cf1c26396064fabdecfab1d9abb47962

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
